---
- name: "Ansible Playbook to deploy Springboot application"
  hosts: localhost
  tasks:
    - name: "Update the packages with package repository"
      shell: apt update && apt upgrade -y
      when: ansible_distribution == 'Ubuntu'
    - name: "Update the packages with package repository when centos"
      shell: yum update
      when: ansible_distribution == 'CentOS'
    - name: "Install Tomcat server in Ubuntu"
      shell: |
        cd /root
        wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.76/bin/apache-tomcat-9.0.76.tar.gz
        tar -xvzf apache-tomcat-9.0.76.tar.gz
        cd apache-tomcat-9.0.76/bin
        bash startup.sh
    - name: 'Clone the git repository'
      shell: |
        cd /root
        git clone https://github.com/lokeshb003/Petclinic
        cd Petclinic
        mvn clean package -DskipTests=true
        cp target/petclinic.war /root/apache-tomcat-9.0.76/webapps
    - name: 'reboot the tomcat server'
      shell: |
        cd /root/apache-tomcat-9.0.76/bin
        bash shutdown.sh
        bash startup.sh